name: Secret Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan on Sundays

jobs:
  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run secret detection
        run: node scripts/vault-manager.js --scan
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  trufflehog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.16.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  detect-aws-credentials:
    name: Detect AWS Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect AWS Credentials
        uses: apex/actions/aws/detect-credentials@master

  detect-env-secrets:
    name: Detect Environment Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find .env files
        id: find-env
        run: |
          ENV_FILES=$(find . -name ".env*" -not -path "*/node_modules/*" -not -path "*/vendor/*" | tr '\n' ' ')
          echo "ENV_FILES=$ENV_FILES" >> $GITHUB_ENV

      - name: Check .env files for secrets
        if: env.ENV_FILES != ''
        run: |
          for file in $ENV_FILES; do
            echo "Checking $file for secrets..."
            grep -E "(API_KEY|SECRET|PASSWORD|TOKEN|KEY)=" $file && echo "Potential secrets found in $file" || echo "No obvious secrets found in $file"
          done

  security-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    needs: [detect-secrets, trufflehog, gitleaks, detect-aws-credentials, detect-env-secrets]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate report
        run: |
          echo "# Secret Scanning Report" > secret-report.md
          echo "## Summary" >> secret-report.md
          echo "Secret scan completed on $(date)" >> secret-report.md
          
          echo "### Results by Tool" >> secret-report.md
          echo "- Custom Secret Detection: ${{ needs.detect-secrets.result }}" >> secret-report.md
          echo "- TruffleHog: ${{ needs.trufflehog.result }}" >> secret-report.md
          echo "- Gitleaks: ${{ needs.gitleaks.result }}" >> secret-report.md
          echo "- AWS Credentials Detection: ${{ needs.detect-aws-credentials.result }}" >> secret-report.md
          echo "- Environment File Check: ${{ needs.detect-env-secrets.result }}" >> secret-report.md

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: secret-scanning-report
          path: secret-report.md
